name: Validate CloudFormation

on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Run cfn-lint (all YAML files)
        run: |
          # find all yaml files in repository and lint them
          files=$(git ls-files '*.yml' '*.yaml' || true)
          if [ -z "$files" ]; then
            echo "No YAML files to lint"
            exit 0
          fi
          echo "Linting: $files"
          for f in $files; do
            echo "---- Linting $f ----"
            cfn-lint -i E1016 -i E1018 "$f" || (echo "cfn-lint failed for $f" && exit 1)
          done
